services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend