services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # <--- THIS IS THE ROTATION
        max-file: "3"

  backend:
    image: test-backend
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend